module.exports = [
  "midas staff",
  "midas' sword",
  "soulstealer bow",
  "dreadlord sword",
  "machine gun bow",
  "zombie soldier cutlass",
  "end stone bow",
  "ender bow",
  "earth shard",
  "zombie knight sword",
  "sniper bow",
  "conjuring",
  "silver fang",
  "zombie commander whip",
  "tactician's sword",
  "hunter knife",
  "silent death",
  "recluse fang",
  "undead bow",
  "super cleaver",
  "fel sword",
  "end stone sword",
  "spider queen's stinger",
  "clouds networth",
  "shaman sword",
  "raider axe",
  "golem sword",
  "pink wool",
  "furnace",
  "piston",
  "sea lantern",
  "chest",
  "trap",
  "superboom tnt",
  "plumber's sponge",
  "endstone rose",
  "scarf fragment",
  "block of diamond",
  "bonzo fragment",
  "minion expander",
  "red sandstone slab",
  "barrier",
  "teleport pad",
  "parkour start/end",
  "dungeon chest key",
  "hyper furnace",
  "beacon block",
  "hilt of true ice",
  "very damaged anvil",
  "kat flower",
  "great carrot candy",
  "slightly damaged anvil",
  "end portal frame",
  "large storage",
  "beacon i",
  "lava (no spread)",
  "cocoa plant",
  "golden boots",
  "happy mask",
  "miner boots",
  "miner leggings",
  "miner chestplate",
  "miner helmet",
  "goblin boots",
  "goblin leggings",
  "goblin chestplate",
  "goblin helmet",
  "glacite boots",
  "glacite leggings",
  "glacite chestplate",
  "glacite helmet",
  "sniper helmet",
  "rotten boots",
  "rotten  leggings",
  "rotten chestplate",
  "rotten helmet",
  "zombie solider boots",
  "zombie solider leggings",
  "zombie solider chestplate",
  "zombie solider helmet",
  "heavy boots",
  "heavy leggings",
  "heavy chestplate",
  "heavy helmet",
  "skeleton grunt boots",
  "skeleton grunt leggings",
  "skeleton grunt chestplate",
  "skeleton grunt helmet",
  "skeleton soldier boots",
  "skeleton soldier leggings",
  "skeleton soldier chestplate",
  "skeleton soldier helmet",
  "obsidian chestplate",
  "lapis armor boots",
  "lapis armor leggings",
  "lapis armor chestplate",
  "lapis armor helmet",
  "skeleton master boots",
  "skeleton master leggings",
  "skeleton master chestplate",
  "skeleton master helmet",
  "skeletor boots",
  "skeletor leggings",
  "skeletor chestplate",
  "skeletor helmet",
  "hardened diamond boots",
  "hardened diamond leggings",
  "hardened diamond chestplate",
  "hardened diamond helmet",
  "bouncy boots",
  "bouncy leggings",
  "bouncy chestplate",
  "bouncy helmet",
  "ember boots",
  "ember leggings",
  "ember chestplate",
  "ember helmet",
  "guardian chestplate",
  "salmon boots",
  "salmon leggings",
  "salmon chestplate",
  "salmon helmet",
  "snow suit boots",
  "snow suit leggings",
  "snow suit chestplate",
  "snow suit helmet",
  "zombie knight boots",
  "zombie knight leggings",
  "zombie knight chestplate",
  "zombie knight helmet",
  "zombie commander boots",
  "zombie commander leggings",
  "zombie commander chestplate",
  "zombie commander helmet",
  "fairy's galoshes",
  "fairy's trousers",
  "fairy's polo",
  "fairy's fedora",
  "mithril coat",
  "farm armor boots",
  "farm armor leggings",
  "farm armor chestplate",
  "farm armor helmet",
  "skeleton lord boots",
  "skeleton lord leggings",
  "skeleton lord chestplate",
  "skeleton lord helmet",
  "super heavy boots",
  "super heavy leggings",
  "super heavy chestplate",
  "super heavy helmet",
  "zombie lord boots",
  "zombie lord leggings",
  "zombie lord chestplate",
  "zombie lord helmet",
  "witch mask",
  "golem armor boots",
  "golem armor leggings",
  "golem armor chestplate",
  "golem armor helmet",
  "mender helmet",
  "ender boots",
  "ender leggings",
  "ender chestplate",
  "ender helmet",
  "water hydra head",
  "dark goggles",
  "krampus helmet",
  "ghostly boots",
  "lantern helmet",
  "holy dragon boots",
  "holy dragon leggings",
  "holy dragon chestplate",
  "holy dragon helmet",
  "unstable dragon boots",
  "unstable dragon leggings",
  "unstable dragon chestplate",
  "unstable dragon helmet",
  "old dragon boots",
  "old dragon leggings",
  "old dragon chestplate",
  "old dragon helmet",
  "protector dragon boots",
  "protector dragon leggings",
  "protector dragon chestplate",
  "protector dragon helmet",
  "revenant boots",
  "revenant leggings",
  "fallen star helmet",
  "farmer boots",
  "crystal boots",
  "crystal helmet",
  "zombie's heart",
  "spider's boots",
  "skeleton's helmet",
  "bonzo's mask",
  "necromancer lord helmet",
  "speedster boots",
  "speedster helmet",
  "armor of the magma boots",
  "armor of the magma leggings",
  "armor of the magma chestplate",
  "armor of the magma helmet",
  "adaptive boots",
  "mineral boots",
  "mineral helmet",
  "tarantula leggings",
  "mystical mushroom soup",
  "healing tissue",
  "bottle of jyrre",
  "premium flesh",
  "lapis crystal",
  "gem rune i",
  "gem rune ii",
  "gem rune iii",
  "white spiral rune i",
  "white spiral rune ii",
  "white spiral rune iii",
  "snow rune i",
  "snow rune ii",
  "snow rune iii",
  "molten cube",
  "inflatable jerry",
  "rare diamond",
  "hunk of ice",
  "hunk of blue ice",
  "zap rune i",
  "zap rune ii",
  "zap rune iii",
  "lava rune i",
  "lava rune ii",
  "lava rune iii",
  "hot rune i",
  "hot rune ii",
  "hot rune iii",
  "wooden pickaxe",
  "wooden shovel",
  "wooden hoe",
  "wooden axe",
  "sparkling rune i",
  "sparkling rune ii",
  "sparkling rune iii",
  "bone meal",
  "winter disc",
  "beating heart",
  "ice rune i",
  "ice rune ii",
  "ice rune iii",
  "salmon opal",
  "onyx",
  "egg stack",
  "spirit leap",
  "journal entry",
  "travel scroll to spider's den top of nest",
  "goblin egg",
  "red nose",
  "fel pearl",
  "optical lens",
  "hay bale",
  "tepid green tea",
  "hearts rune i",
  "hearts rune ii",
  "hearts rune iii",
  "wand of healing",
  "spider catalyst",
  "undead catalyst",
  "dungeon orb",
  "small backpack",
  "diamond spreading",
  "ember fragment",
  "weapon rack",
  "battle disc",
  "suspicious vial",
  "polished pebble",
  "armor stand",
  "revenant catalyst",
  "bite rune i",
  "bite rune ii",
  "bite rune iii",
  "experimentation table",
  "pestience rune i",
  "pestience rune ii",
  "pestience rune iii",
  "frosty the snow cannon",
  "dragon scale",
  "toxic arrow poison",
  "remant of the eye",
  "golden rune i",
  "golden rune ii",
  "golden rune iii",
  "candy corn",
  "silent pearl",
  "soul string",
  "desert island",
  "beach ball",
  "cheap coffee",
  "trick or treat bag",
  "grappling hook",
  "bigfoot's lasso",
  "decoy",
  "easter basket",
  "silky lichen",
  "portal to jungle island",
  "clouds rune i",
  "clouds rune ii",
  "clouds rune iii",
  "nether wart island",
  "portal to birch park",
  "blood rune i",
  "blood rune ii",
  "blood rune iii",
  "beheaded horror",
  "arachne fragment",
  "redstone rune i",
  "redstone rune ii",
  "redstone rune iii",
  "nutcracker",
  "present stack",
  "grinch minion skin",
  "reppeling candle",
  "volta",
  "plasma",
  "flower bed",
  "egg pile",
  "radiant power orb",
  "roofed forest island",
  "chest storage",
  "personal bank item",
  "medium backpack",
  "carrot patch",
  "sled",
  "portal to mushroom island",
  "carpentry table",
  "snow shovel",
  "rock paper shears",
  "wake rune i",
  "wake rune ii",
  "wake rune iii",
  "gingerbread man minion skin",
  "arachne's keeper fragment",
  "magical rune i",
  "magical rune ii",
  "magical rune iii",
  "blast o' lantern",
  "portal to dark thicket",
  "jolly pink rock",
  "sorrow",
  "chick nest",
  "portal to the deep caverns",
  "travel scroll to howling cave",
  "mimic fragment",
  "rock candy",
  "tic tac toe",
  "tall holiday tree",
  "weak wolf catalyst",
  "cyan reppeling candle",
  "skeleton skull",
  "bunny",
  "decent coffee",
  "magical milk bucket",
  "golden powder",
  "beach chair",
  "bitter ice tea",
  "true essence",
  "stocking",
  "necromancer's brooch",
  "lightning rune i",
  "lightning rune ii",
  "lightning rune iii",
  "cola cooler",
  "pink repelling candle",
  "lilac repelling candle",
  "blue repelling candle",
  "purple repelling candle",
  "orange repelling candle",
  "aqua repelling candle",
  "green repelling candle",
  "hypixel sandcastle",
  "weapon rack+",
  "viking's tear",
  "minion chair",
  "halloween candles",
  "tutti-frutti flavored poison",
  "dwarvern tnakard",
  "rabbit hutch",
  "glacite jewel",
  "enchanting table+",
  "accessory enrichment swapper",
  "training dummy",
  "echolocator",
  "ice lolly minion skin",
  "pond island",
  "furnace+",
  "star decorations",
  "diamond atom",
  "wand of mending",
  "jerry candy",
  "portal to the barn",
  "winter rod",
  "egg hunt",
  "spooky disc",
  "portal to the spider's den",
  "midas jewel",
  "wood chest+",
  "treasurite",
  "travel scroll to magma fields",
  "rainbow rune i",
  "rainbow rune ii",
  "rainbow rune iii",
  "gingerbread house",
  "ice rod",
  "chicken coop",
  "hyper catalyst upgrade",
  "sun minion skin",
  "livid fragment",
  "sandcastle minion skin",
  "ancestral spade",
  "red tent",
  "picnic set",
  "derpy snowman",
  "live preserver",
  "reindeer plush",
  "sleeping eye",
  "crystal fragment",
  "flying bats",
  "travel scroll to the barn",
  "easter egg minion skin",
  "travel scroll to the deep caverns",
  "luxurious spool",
  "travel scroll to jungle island",
  "spirit rune i",
  "spirit rune ii",
  "spirit rune iii",
  "fire spiral rune i",
  "fire spiral rune ii",
  "fire spiral rune iii",
  "lesser orb of healing",
  "coffin",
  "emperor's skull",
  "large backpack",
  "saddle",
  "bat firework",
  "melon minion skin",
  "dirt bottle",
  "smokey rune i",
  "smokey rune ii",
  "smokey rune iii",
  "travel scroll to blazing fortress",
  "diamond chest+",
  "travel scroll to mushroom island",
  "bunny minion skin",
  "petrified starfall",
  "four in a row",
  "travel scroll to the park",
  "red claw egg",
  "small holiday tree",
  "bbq grill",
  "frosty the snow blaster",
  "bejeweled handle",
  "reindeer minion skin",
  "hermit crab minion skin",
  "flower pot",
  "pumpkin minion skin",
  "endstone chest+",
  "scarecrow",
  "jingle bells",
  "white repelling candle",
  "ghost minion skin",
  "travel scroll to hub castle",
  "red scarf",
  "travel scroll to the end",
  "dark queen's soul drop",
  "garland",
  "desk",
  "ghost book",
  "snake rune i",
  "candy bowl",
  "l.a.s.r.'s eye",
  "rod of champions",
  "horseman's candle",
  "biofuel",
  "candle arch",
  "yeti rod",
  "restone chest+",
  "present minion skin",
  "couture rune i",
  "emerald chest+",
  "travel scroll to the gold mine",
  "undead minion skin",
  "bee minion skin",
  "zombie grave",
  "mummy candle",
  "kismet feather",
  "dark orb",
  "greater backpack",
  "illusion glass",
  "crochet tiger plushie",
  "god potion",
  "jerry stone",
  "dragon claw",
  "beach ball minion skin",
  "colossal experience bottle upgrade",
  "stonk",
  "personal harp",
  "dingy",
  "bunny jerry",
  "wizard's crystal",
  "creeper skull",
  "adaptive blade",
  "adaptive helm",
  "adaptive chestplate",
  "adaptive leggings",
  "adaptive boots",
  "emerald armor helmet",
  "emerald armor chestplate",
  "emerald armor leggings",
  "emerald armor boots",
  "redstone key",
  "stereo pants",
  "wither skeleton skull",
  "iron horse armor",
  "gold horse armor",
  "diamond horse armor",
  "fractured mithril pickaxe",
  "bandaged mithril pickaxe",
  "titanium pickaxe",
  "name tag",
  "wreath",
  "ender chest+",
  "tasty cheese",
  "crystal ball",
  "staff of the rising sun",
  "helmet of the rising sun",
  "chestplate of the rising sun",
  "leggings of the rising sun",
  "boots of the rising sun",
  "skull chest++"
];