module.exports = [
  "soulstealer bow",
  "dreadlord sword",
  "machine gun bow",
  "zombie soldier cutlass",
  "end stone bow",
  "ender bow",
  "earth shard",
  "zombie knight sword",
  "sniper bow",
  "conjuring",
  "silver fang",
  "zombie commander whip",
  "tactician’s sword",
  "hunter knife",
  "silent death",
  "recluse fang",
  "undead bow",
  "super cleaver",
  "fel sword",
  "end stone sword",
  "spider queen’s stinger",
  "clouds networth",
  "shaman sword",
  "raider axe",
  "golem sword",
  "pink wool",
  "furnace",
  "piston",
  "sea lantern",
  "chest",
  "trap",
  "superboom tnt",
  "plumber’s sponge",
  "endstone rose",
  "scarf fragment",
  "block of diamond",
  "bonzo fragment",
  "minion expander",
  "red sandstone slab",
  "barrier",
  "teleport pad",
  "parkour start/end",
  "dungeon chest key",
  "hyper furnace",
  "beacon block",
  "hilt of true ice",
  "very damaged anvil",
  "kat flower",
  "great carrot candy",
  "slightly damaged anvil",
  "end portal frame",
  "large storage",
  "beacon i",
  "lava (no spread)",
  "cocoa plant",
  "golden boots",
  "happy mask",
  "miner boots",
  "miner leggings",
  "miner chestplate",
  "miner helmet",
  "goblin boots",
  "goblin leggings",
  "goblin chestplate",
  "goblin helmet",
  "glacite boots",
  "glacite leggings",
  "glacite chestplate",
  "glacite helmet",
  "sniper helmet",
  "rotten boots",
  "rotten  leggings",
  "rotten chestplate",
  "rotten helmet",
  "zombie solider boots",
  "zombie solider leggings",
  "zombie solider chestplate",
  "zombie solider helmet",
  "heavy boots",
  "heavy leggings",
  "heavy chestplate",
  "heavy helmet",
  "skeleton grunt boots",
  "skeleton grunt leggings",
  "skeleton grunt chestplate",
  "skeleton grunt helmet",
  "skeleton soldier boots",
  "skeleton soldier leggings",
  "skeleton soldier chestplate",
  "skeleton soldier helmet",
  "obsidian chestplate",
  "lapis armor boots",
  "lapis armor leggings",
  "lapis armor chestplate",
  "lapis armor helmet",
  "skeleton master boots",
  "skeleton master leggings",
  "skeleton master chestplate",
  "skeleton master helmet",
  "skeletor boots",
  "skeletor leggings",
  "skeletor chestplate",
  "skeletor helmet",
  "hardened diamond boots",
  "hardened diamond leggings",
  "hardened diamond chestplate",
  "hardened diamond helmet",
  "bouncy boots",
  "bouncy leggings",
  "bouncy chestplate",
  "bouncy helmet",
  "ember boots",
  "ember leggings",
  "ember chestplate",
  "ember helmet",
  "guardian chestplate",
  "salmon boots",
  "salmon leggings",
  "salmon chestplate",
  "salmon helmet",
  "snow suit boots",
  "snow suit leggings",
  "snow suit chestplate",
  "snow suit helmet",
  "zombie knight boots",
  "zombie knight leggings",
  "zombie knight chestplate",
  "zombie knight helmet",
  "zombie commander boots",
  "zombie commander leggings",
  "zombie commander chestplate",
  "zombie commander helmet",
  "fairy’s galoshes",
  "fairy’s trousers",
  "fairy’s polo",
  "fairy’s fedora",
  "mithril coat",
  "farm armor boots",
  "farm armor leggings",
  "farm armor chestplate",
  "farm armor helmet",
  "skeleton lord boots",
  "skeleton lord leggings",
  "skeleton lord chestplate",
  "skeleton lord helmet",
  "super heavy boots",
  "super heavy leggings",
  "super heavy chestplate",
  "super heavy helmet",
  "zombie lord boots",
  "zombie lord leggings",
  "zombie lord chestplate",
  "zombie lord helmet",
  "witch mask",
  "golem armor boots",
  "golem armor leggings",
  "golem armor chestplate",
  "golem armor helmet",
  "mender helmet",
  "ender boots",
  "ender leggings",
  "ender chestplate",
  "ender helmet",
  "water hydra head",
  "dark goggles",
  "krampus helmet",
  "ghostly boots",
  "lantern helmet",
  "holy dragon boots",
  "holy dragon leggings",
  "holy dragon chestplate",
  "holy dragon helmet",
  "unstable dragon boots",
  "unstable dragon leggings",
  "unstable dragon chestplate",
  "unstable dragon helmet",
  "old dragon boots",
  "old dragon leggings",
  "old dragon chestplate",
  "old dragon helmet",
  "protector dragon boots",
  "protector dragon leggings",
  "protector dragon chestplate",
  "protector dragon helmet",
  "revenant boots",
  "revenant leggings",
  "fallen star helmet",
  "farmer boots",
  "crystal boots",
  "crystal helmet",
  "zombie’s heart",
  "spider’s boots",
  "skeleton’s helmet",
  "bonzo’s mask",
  "necromancer lord helmet",
  "speedster boots",
  "speedster helmet",
  "armor of the magma boots",
  "armor of the magma leggings",
  "armor of the magma chestplate",
  "armor of the magma helmet",
  "adaptive boots",
  "mineral boots",
  "mineral helmet",
  "tarantula leggings",
  "mystical mushroom soup",
  "healing tissue",
  "bottle of jyrre",
];
